kind = "web"
previewPath = "/"
title = "Vision 2020 Conference 2026"
version = "1.0.0"
id = "artifacts/vision2020"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24212

[services.development]
run = "pnpm --filter @workspace/vision2020 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vision2020", "run", "build" ]
publicDir = "artifacts/vision2020/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24212"
BASE_PATH = "/"
